services:
  sherbinki3-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sherbinki3-service
    image: sherbinki3-service:latest
    env_file:
      - environment/postgres.env
      - environment/jwt.env
      - environment/redis.env
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16.1
    container_name: pgsql-sherbinki3
    env_file:
      - environment/postgres.env
    ports:
      - 5432:5432

  redis:
    image: redis:7.2.4
    container_name: redis-sherbinki3-jwt
    ports:
      - 6379:6379