package ru.stm.shcherbinki3.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Objects;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Data Transfer Object representing a user")
public class UserDto {

    @Schema(
            description = "Unique identifier of the user (automatically generated by the system)",
            example = "1"
    )
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Long id;

    @Schema(
            description = "User's email address used for authentication and communication",
            example = "a.v.sybachin@mail.ru"
    )
    @NotNull(message = "Email cannot be null")
    @Email(message = "Email must be a valid email address")
    @Size(max = 255, message = "Email must be at most 255 characters")
    private String email;

    @Schema(
            description = "User's password. Provided only during registration or when changing the password." +
                    "Must be at least 8 characters long",
            example = "Qwerty123!"
    )
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @NotBlank(message = "Password cannot be null")
    @Size(min = 8, max = 255, message = "Password must be between 8 and 255 characters long")
    private String password;

    @Schema(
            description = "User's first name",
            example = "Alexander"
    )
    @NotBlank(message = "Name cannot be null")
    @Size(min = 2, max = 120, message = "Name must be between 2 and 120 characters long")
    private String name;

    @Schema(
            description = "User's last name",
            example = "Sybachin"
    )
    @NotBlank(message = "Lastname cannot be null")
    @Size(min = 2, max = 120, message = "Lastname must be between 2 and 120 characters long")
    private String lastname;

    @Schema(
            description = "User's middle name (optional)",
            example = "Vasilyevich"
    )
    @Size(min = 2, max = 120, message = "Patronymic must be between 2 and 120 characters long")
    private String patronymic;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UserDto dto)) return false;

        if (id != null && dto.id != null) {
            return Objects.equals(id, dto.getId());
        }

        return Objects.equals(email, dto.getEmail());
    }

    @Override
    public int hashCode() {
        if (id != null) {
            return id.hashCode();
        }
        return Objects.hash(email);
    }

    @Override
    public String toString() {
        return "UserDto{" +
                "id=" + id +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                ", name='" + name + '\'' +
                ", lastname='" + lastname + '\'' +
                ", patronymic='" + patronymic + '\'' +
                '}';
    }
}