CREATE TABLE IF NOT EXISTS carrier (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(11),
    record_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    deleted_datetime TIMESTAMP
);