CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(120) NOT NULL,
    lastname VARCHAR(120) NOT NULL,
    patronymic VARCHAR(120),
    record_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
);
